import {useEffect,useState} from 'react';
import {CheckCircle2,Loader2,Phone,ShieldCheck} from 'lucide-react';
import {phoneAgentsApi,type ClientPhoneAgent} from '@/api/phoneAgents';
import {outboundCallsApi,type OutboundAgent} from '@/api/outboundCalls';

const card='rounded-2xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900';
export default function CallingPage(){
 const[agents,setAgents]=useState<ClientPhoneAgent[]>([]),[selected,setSelected]=useState<ClientPhoneAgent|null>(null),[outbound,setOutbound]=useState<OutboundAgent[]>([]),[name,setName]=useState(''),[number,setNumber]=useState(''),[consent,setConsent]=useState(false),[message,setMessage]=useState(''),[sending,setSending]=useState(false);
 useEffect(()=>{Promise.allSettled([phoneAgentsApi.list(),outboundCallsApi.list()]).then(([agentResult,outboundResult])=>{if(agentResult.status==='fulfilled'){setAgents(agentResult.value);setSelected(agentResult.value[0]||null)}else setMessage('Unable to load the assigned phone agent.');if(outboundResult.status==='fulfilled')setOutbound(outboundResult.value);else setMessage('Unable to load outbound calling configuration. Refresh the page or contact your administrator.')})},[]);
 const config=outbound[0];const ready=!!config&&config.platform_enabled&&config.enabled&&(config.mode==='outbound'||config.mode==='both')&&config.status==='active'&&!!config.outbound_trunk_id;
 const reasons=!config?['No outbound configuration is assigned.']:[!config.platform_enabled?'Outbound calling is paused by the administrator.':'',!config.enabled?'This agent is not enabled for outbound calls.':'',config.mode==='inbound'?'This agent is configured for inbound calls only.':'',!config.outbound_trunk_id?'No outbound trunk is assigned.':''].filter(Boolean);
 const call=async()=>{if(!config||!ready)return;if(!name.trim()||!number.trim()||!consent){setMessage('Enter a contact, use an international number, and confirm consent.');return}setSending(true);setMessage('');try{const result=await outboundCallsApi.create({phone_agent_id:config.id,destination:number,contact_name:name,consent_confirmed:consent});setMessage(`Call queued (${result.id}). The status will update in call history.`);setName('');setNumber('');setConsent(false)}catch(e:any){const d=e.response?.data?.detail;setMessage(typeof d==='string'?d:d?.reasons?.join(' · ')||d?.message||'Call could not be queued.')}finally{setSending(false)}};
 return <div className="space-y-6"><div><h1 className="text-2xl font-bold text-slate-900 dark:text-white">AI Calling</h1><p className="mt-1 text-sm text-slate-500">Manage your telephone agent and place consented outbound calls.</p></div>
 <div className="grid gap-4 sm:grid-cols-3"><div className={`${card} p-4`}><div className="text-xs text-slate-500">Status</div><div className="mt-1 flex items-center gap-2 font-bold"><CheckCircle2 size={17} className="text-emerald-500"/>{selected?.status||'Pending'}</div></div><div className={`${card} p-4`}><div className="text-xs text-slate-500">Assigned number</div><div className="mt-1 font-bold">{selected?.dids.map(d=>d.did).join(', ')||'Pending'}</div></div><div className={`${card} p-4`}><div className="text-xs text-slate-500">Capacity</div><div className="mt-1 font-bold">{selected?.dids.reduce((n,d)=>n+d.channel_limit,0)||0} concurrent call(s)</div></div></div>
 {agents.length>1&&<select className="rounded-xl border p-3 dark:bg-slate-900" value={selected?.id||''} onChange={e=>setSelected(agents.find(a=>a.id===e.target.value)||null)}>{agents.map(a=><option key={a.id} value={a.id}>{a.display_name}</option>)}</select>}
 <div className="grid gap-5 lg:grid-cols-2"><section className={`${card} p-5`}><div className="flex items-center gap-2"><Phone className="text-violet-600"/><h2 className="text-lg font-bold">Place an outbound call</h2></div>{ready?<div className="mt-5 space-y-4"><label className="block text-sm font-medium">Contact name<input className="mt-1 w-full rounded-xl border bg-transparent p-3" value={name} onChange={e=>setName(e.target.value)} placeholder="Customer name"/></label><label className="block text-sm font-medium">Phone number<input className="mt-1 w-full rounded-xl border bg-transparent p-3" value={number} onChange={e=>setNumber(e.target.value)} placeholder="+919876543210"/><span className="mt-1 block text-xs text-slate-500">Include country code in E.164 format.</span></label><label className="flex items-start gap-3 rounded-xl border p-3 text-sm"><input type="checkbox" className="mt-1" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>I confirm this recipient has consented to receive this call and the call complies with applicable rules.</span></label><button onClick={call} disabled={sending} className="flex w-full items-center justify-center gap-2 rounded-xl bg-violet-600 p-3 font-semibold text-white disabled:opacity-50">{sending?<Loader2 className="animate-spin" size={18}/>:<Phone size={18}/>}Start outbound call</button></div>:<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-300"><strong>Outbound calls are not available yet.</strong><ul className="mt-2 list-disc space-y-1 pl-5">{reasons.map(r=><li key={r}>{r}</li>)}</ul></div>}{message&&<p className="mt-4 rounded-xl bg-slate-100 p-3 text-sm dark:bg-slate-800">{message}</p>}</section>
 <section className={`${card} p-5`}><div className="flex items-center gap-2"><ShieldCheck className="text-violet-600"/><h2 className="text-lg font-bold">Call safeguards</h2></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="text-slate-500">Daily call limit</dt><dd className="font-semibold">{config?.daily_limit??'—'}</dd></div><div><dt className="text-slate-500">Maximum call duration</dt><dd className="font-semibold">{config?`${Math.round(config.max_duration_seconds/60)} minutes`:'—'}</dd></div><div><dt className="text-slate-500">Caller ID</dt><dd className="font-semibold">{config?.did||'Not assigned'}</dd></div><div><dt className="text-slate-500">Agent mode</dt><dd className="font-semibold capitalize">{config?.mode||'—'}</dd></div></dl></section></div></div>;
}
